services:
  mathflix-frontend:
    image: ghcr.io/ferilee/mathflix:latest
    container_name: mathflix-frontend
    ports:
      - "9101:80"
    environment:
      - VITE_API_URL=http://api-mathflix:3001
    restart: unless-stopped
